### ISSUE TITLE
[Bug]: Scroll-Snap CSS breaks horizontal scrolling

### ISSUE THREAD

**Issue by jamesarosen** [ceolter/ag-grid#10667]
### Link to reproducible scenario

https://codesandbox.io/p/sandbox/column-ids-forked-jym6q2

### Steps to reproduce 
1. create a grid with a large number of columns
2. add CSS scroll-snap to the header and body

```css
.ag-header-viewport,
.ag-center-cols-viewport {
  scroll-snap-type: x mandatory;
}

.ag-cell,
.ag-header-cell {
  scroll-snap-align: start;
}
```

### Actual behaviour
* Scrolling gradually with a wheel works well
* Scrolling all the way immediately to the start or the end of the table omits the start or end, respectively, of the contents

### Expected behaviour
* The scrollbar matches the actual content of the table

### More information

If you grab the scrollbar and quickly scroll all the way to the start or end, the window only scrolls a portion of the columns. If you then scrub back and forth near the start/end, the remaining columns pop in.

https://github.com/user-attachments/assets/b62840bc-c8f2-4767-9a09-cc35c012e2e5

Related: [#8330](https://github.com/ag-grid/ag-grid/issues/8330)

### Version

32.3.5

### Does the issue occur for a specific framework only?

React

### Is the issue only observable on a specific browser?

Chrome
