### ISSUE TITLE
.ag-rtl classnames  breaks normal rtl behaviour

### ISSUE THREAD

**Issue by irsooti** [ceolter/ag-grid#4711]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

Hello, I'm using @ag-grid-community/react. On the component `<AgGridReact />` I'm providing `enableRtl=true` in order to display data using the HTML direction (eq: Arabic <-rtl).
This rule seems to break the order:

```css
.ag-rtl .ag-body, .ag-rtl .ag-floating-top, .ag-rtl .ag-floating-bottom, .ag-rtl .ag-header, .ag-rtl .ag-body-viewport, .ag-rtl .ag-body-horizontal-scroll {

flex-direction: row-reverse;
}
```

Is it an intentional behavior or just a refusal?

Thanks in advance

version: 24.1.1
