### ISSUE TITLE
[Question] - Is there any way to made the parent ``headerName`` goes to center?

### ISSUE THREAD

**Issue by adiatma85** [ceolter/ag-grid#9721]
Context:

![Image](https://github.com/user-attachments/assets/35cb46c5-a948-4cc0-b2c1-d975c2bbd86c)

Is ag-grid support header name customization so the name ("Monthly breakdown" in this case) goes to center instead in the left? You can imagine it as a excel or google spreadsheet. This is what I am trying right now:

```css
.general_header {
  background-color: #92cddc;
  text-align: center; /* Align text within the cell */
  display: flex;
  align-items: center; /* Center vertically */
  justify-content: center; /* Center horizontally */
  color: black;
}
```

But the parent header name is still intact in left like this:

![Image](https://github.com/user-attachments/assets/523d9eda-3bc0-4fc9-96b8-1ac8df0caba3)

Thanks in advance
