### ISSUE TITLE
[Support]: Filter icons do not hide / show on hover in ag-grid 33

### ISSUE THREAD

**Issue by rakkur** [ceolter/ag-grid#9952]
### Add a description

Is there any way to restore the functionality where the filter buttons are hidden until the user hovers over the header they wish to modify?  We have 11-12 columns and showing all the filter buttons at once makes the page incredibly busy.  We also have sidebars with multiple tables that all now have permanently visible icons.

I searched through the documentation and could not find any easy way to accomplish this.

Old version:

![Image](https://github.com/user-attachments/assets/c48daef3-c21a-46f2-ae70-4437677b703a)

New version:

![Image](https://github.com/user-attachments/assets/85f71846-a718-4051-8866-8934052e206e)

### Version

Migrated from 31.2.0 to 33.1.0

### What language are you using?

TypeScript

### What browser are you using?

Firefox

**Comment by remkodejong** [comment]
I second this, would be nice to have the filter button work the same as the legacy menu button, so show and hide on column header hover. We have no need for the menu button so great that we can suppress that but it is rather busy with all those filter buttons on top.

For now I've fixed it with CSS:

```css
.ag-header-cell {
  .ag-header-cell-filter-button {
    display: none;
  }
  &.ag-header-cell-filtered,
  &.ag-column-menu-visible,
  &.ag-header-active {
    .ag-header-cell-filter-button {
      display: initial;
    }
  }
}
```
